version: "3"
services:

  gateway:
    image: nginx:1.25-bookworm
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - stock-service
      - payment-service
    networks:
      - app_network

  order-service:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/order_redis.env
    depends_on:
      - order-db
    networks:
      - app_network

  order-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb
    networks:
      - app_network

  stock-service:
    build: ./stock
    image: stock:latest
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/stock_redis.env
    depends_on:
      - stock-db
    networks:
      - app_network

  stock-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb
    networks:
      - app_network

  payment-service:
    build: ./payment
    image: user:latest
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/payment_redis.env
    depends_on:
      - payment-db
    networks:
      - app_network

  payment-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb
    networks:
      - app_network

  order-postgres:
    image: postgres:15.2
    user: postgres
    environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"
    - "POSTGRES_USER=postgres"
    - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5431:5432"
    networks:
      - app_network

  stock-postgres:
    image: postgres:15.2
    user: postgres
    environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"
    - "POSTGRES_USER=postgres"
    - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
    networks:
      - app_network

  payment-postgres:
    image: postgres:15.2
    user: postgres
    environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"
    - "POSTGRES_USER=postgres"
    - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5433:5432"
    networks:
      - app_network

  # pgAdmin (access with localhost:5050 in browser)
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
